# Generated by Django 2.2 on 2020-08-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='personil',
            field=models.TextField(default='(Personil)'),
        ),
        migrations.AddField(
            model_name='band',
            name='posisi',
            field=models.TextField(default='(Posisi)'),
        ),
        migrations.AddField(
            model_name='band',
            name='status',
            field=models.TextField(default='(Status)'),
        ),
        migrations.AlterField(
            model_name='band',
            name='aliran',
            field=models.TextField(default='(Aliran)'),
        ),
        migrations.AlterField(
            model_name='band',
            name='nama_band',
            field=models.TextField(default='(Nama Band)'),
        ),
        migrations.AlterField(
            model_name='band',
            name='negara_asal',
            field=models.TextField(default='(Negara Asal)'),
        ),
    ]
