# Generated by Django 2.2 on 2020-09-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20200828_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.TextField(default='(Nama Band)')),
                ('label', models.TextField(default='(Aliran)')),
            ],
        ),
    ]
