# Generated by Django 2.2 on 2020-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0007_auto_20200904_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='aliran',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='label',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='nama_band',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='status',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.TextField(default='(Genre)'),
        ),
    ]
