# Generated by Django 2.2 on 2020-09-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0008_auto_20200904_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='aliran',
            field=models.CharField(default='(Aliran)', max_length=255),
        ),
        migrations.AlterField(
            model_name='band',
            name='label',
            field=models.CharField(default='(Label)', max_length=255),
        ),
        migrations.AlterField(
            model_name='band',
            name='nama_band',
            field=models.CharField(default='(Nama Band)', max_length=255),
        ),
        migrations.AlterField(
            model_name='band',
            name='negara_asal',
            field=models.CharField(default='(Negara Asal)', max_length=255),
        ),
        migrations.AlterField(
            model_name='band',
            name='status',
            field=models.CharField(default='(Status)', max_length=255),
        ),
        migrations.AlterField(
            model_name='band',
            name='tahun',
            field=models.CharField(default='(Tahun)', max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(default='(Genre)', max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='negara_asal',
            field=models.CharField(default='(Negara Asal)', max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='tahun',
            field=models.CharField(default='(Tahun)', max_length=255),
        ),
    ]
