# Generated by Django 2.2 on 2020-10-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='keterangan',
            field=models.TextField(default='Done'),
        ),
    ]
