# Generated by Django 2.2 on 2020-10-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='keterangan',
            field=models.TextField(default='Selesai'),
        ),
    ]
