# Generated by Django 2.2 on 2020-10-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saldoawal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoawal',
            name='i_saldo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
