# Generated by Django 2.2 on 2020-10-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saldoawal', '0002_auto_20201007_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldoawal',
            name='i_saldo',
            field=models.IntegerField(default=0),
        ),
    ]
