# Generated by Django 2.2 on 2020-08-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_band', models.TextField(default='Nama Band')),
                ('aliran', models.TextField(default='Aliran')),
                ('negara_asal', models.TextField(default='Negara Asal')),
            ],
        ),
    ]
