# Generated by Django 2.2 on 2020-09-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0006_auto_20200929_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjualan1m',
            name='saldo_awal',
        ),
    ]
