# Generated by Django 2.2 on 2020-09-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keterangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.TextField(default='(tahun)')),
                ('label', models.TextField(default='(label)')),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
