# Generated by Django 2.2 on 2020-09-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_auto_20200904_0713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keterangan',
            new_name='Genre',
        ),
    ]
