# Generated by Django 2.2 on 2020-09-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0005_auto_20200916_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjualan1m',
            name='jumlah',
        ),
    ]
