# Generated by Django 2.2 on 2020-10-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0003_auto_20201014_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanotif',
            name='tanggal_jatuh_tempo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datanotif',
            name='tanggal_pinjam',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
