# Generated by Django 2.2 on 2020-10-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0005_auto_20201022_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanotif',
            name='tanggal_jatuh_tempo',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='datanotif',
            name='tanggal_pinjam',
            field=models.DateField(auto_now_add=True),
        ),
    ]
