# Generated by Django 2.2 on 2020-10-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0007_auto_20201022_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanotif',
            name='tanggal_jatuh_tempo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='datanotif',
            name='tanggal_pinjam',
            field=models.DateField(),
        ),
    ]
