# Generated by Django 2.2 on 2020-09-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elektronik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elek_image', models.TextField(default='Image')),
                ('elek_name', models.TextField(default='Name')),
                ('elek_stock', models.TextField(default='Stock')),
                ('elek_price', models.TextField(default='Gambar')),
                ('elek_info', models.TextField(default='Info')),
            ],
        ),
    ]
