# Generated by Django 2.2 on 2020-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0005_auto_20200929_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default='tanggal', max_length=255)),
                ('keterangan', models.CharField(default='Keterangan', max_length=255)),
                ('bayar', models.IntegerField()),
                ('hutang', models.IntegerField()),
                ('catatan', models.CharField(default='Catatan', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='saldoawalm',
        ),
    ]
