# Generated by Django 2.2 on 2020-10-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0009_penjualan1m_saldo_awal1'),
    ]

    operations = [
        migrations.CreateModel(
            name='saldoawal1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_awal', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='penjualan1m',
            name='saldo_awal',
        ),
        migrations.RemoveField(
            model_name='penjualan1m',
            name='saldo_awal1',
        ),
    ]
