# Generated by Django 2.2 on 2020-10-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataNotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('hutang', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_jatuh_tempo', models.DateField(auto_now_add=True)),
                ('keterangan', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
